routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('apps', 'AppController')->only(['create', 'store']);

Route::resource('apps.builds', 'AppBuildController')
    ->only(['create', 'store', 'index']);

Route::resource('builds.logs', 'BuildLogController')
    ->only(['index']);

app/App.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class App extends Model
{
    protected $fillable = [
        'app_name',
        'app_display_name',
    ];

    public function builds() {
        return $this->hasMany(\App\Build::class);
    }

    public function unProcessedBuilds() {
        return $this->builds()->where('processed', false);
    }

    public function latestBuild() {
        return $this->builds()->latest()->first();
    }
}

app/Build.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Build extends Model
{
    protected $fillable = [
        'config',
    ];

    protected $casts = [
        'config' => 'json',
    ];

    public function app()
    {
        return $this->belongsTo(\App\App::class);
    }

    public function logs()
    {
        return $this->hasMany(\App\Log::class);
    }
}

app/Log.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    protected $fillable = [
        'type',
        'command',
        'result',
    ];

    public function build()
    {
        return $this->belongsTo(\App\Build::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AppBuildController.php
<?php

namespace App\Http\Controllers;

use App\App;
use Illuminate\Http\Request;
use App\Services\Builds\CreateBuildService;

class AppBuildController extends Controller
{
    public function index(App $app)
    {
        $builds = $app->builds()
            ->orderBy('id', 'DESC')
            ->paginate(5);

        return view('app_build.index', compact('builds', 'app'));
    }

    public function create(App $app)
    {
        $build = $app->builds()->latest()->first();
        return view('app_build.create', compact('build'));
    }

    public function store(Request $request, App $app)
    {
        $config = $request->all();

        (new CreateBuildService($app, $config))->execute();

        return redirect()->route('builds.logs.index', $app->latestBuild());
    }
}

app/Http/Controllers/AppController.php
<?php

namespace App\Http\Controllers;

use App\App;
use App\Http\Requests\FormApp;
use App\Services\App\CreateAppService;

class AppController extends Controller
{

    public function create()
    {
        return view('apps.create');
    }

    public function store(FormApp $request)
    {
        $service = new CreateAppService($request->all());
        $service->execute();
        return redirect()->route('home');
    }
}

app/Http/Controllers/BuildLogController.php
<?php

namespace App\Http\Controllers;

use App\Build;

class BuildLogController extends Controller
{
    public function index(Build $build)
    {
        $logs = $build->logs;
        return view('build_log.index', compact('logs', 'build'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\App;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $apps = App::paginate(5);
        return view('home', compact('apps'));
    }
}

resources/views/app_build/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create New Build for <b>{{ $build->app->app_name}}</b></div>
                <div class="card-body">
                  @include('layouts.partials.errors')

                  <form method="post" action="{{ route('apps.builds.store',['app' => $build->app]) }}" enctype="multipart/form-data" >
                      @csrf
                      @include('app_build.partials.form')
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app_build/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create App</div>
                <div class="card-body">
                  App card
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app_build/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <b> {{$app->app_name}}</b> Builds
                </div>

                <div class="card-body">
                    @component('layouts.components.box', ['title' => 'Builds'])
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Created at</th>
                            <th scope="col">Running?</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($builds as $build)
                            <tr>
                                <th scope="row">{{ $build->id }}</th>
                                <td>{{ $build->created_at->diffForHumans() }}</td>
                                <td>{{ $build->processed }}</td>
                                <td>
                                  <a class="btn btn-link" href="{{ route('builds.logs.index', $build)}}">Assemble Logs</a>
                                </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {{ $builds->links() }}
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app_build/partials/form.blade.php
<form>
  @component('layouts.components.box', ['title' => 'Informações Básica'])
  <div class="row">
    <div class="col-md-6">
        <label for="inputZip">Nome do App</label>
        <input type="text" class="form-control" disabled name="app_name" value="{{ old('app_name') ?? $build->app->app_name }}">
    </div>
    <div class="col-md-6">
        <label for="inputZip">Nome do App no telefone</label>
        <input type="text" class="form-control" disabled name="app_display_name" value="{{ old('app_display_name') ?? $build->app->app_display_name }}" >
    </div>
  </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Definições de Cores'])
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tab_icon_default</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'tab_icon_default')}}" name="config[tab_icon_default]" >
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tint_color</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'tint_color')}}" name="config[tint_color]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tab_bar</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'tab_bar')}}" name="config[tab_bar]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">error_background</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'error_background')}}" name="config[error_background]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">error_text</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'error_text')}}" name="config[error_text]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">warning_background</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'warning_background')}}" name="config[warning_background]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">warning_text</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'warning_text')}}" name="config[warning_text]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">notice_text</label>
          <input type="color" class="form-control" value="{{data_get($build->config, 'notice_text')}}" name="config[notice_text]">
      </div>
    </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Imagens'])
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">Ícone do App (512x512) </label>
          <input type="file"  value="{{data_get($build->config, 'app_icon')}}" name="config[app_icon]">
      </div>

      <div class="col-md-6">
          <label for="inputZip">Splash Screen (2208x2208)</label>
          <input type="file"  value="{{data_get($build->config, 'app_splash_screen')}}" name="config[app_splash_screen]" >
      </div>
    </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Publicação'])
    @component('layouts.components.box', ['title' => 'Credencias do Expo'])
    <div class="row">
        <div class="col-md-6">
            <label for="inputZip">Usuário</label>
            <input type="text" class="form-control" value="{{data_get($build->config, 'expo_user')}}" name="config[expo_user]">
        </div>

        <div class="col-md-6">
            <label for="inputZip">Senha</label>
            <input type="password" class="form-control" value="{{data_get($build->config, 'expo_password')}}" name="config[expo_password]">
        </div>
      </div>
    @endcomponent
  @endcomponent

  <button type="submit" class="btn btn-primary">Create</button>
</form>

resources/views/apps/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create App</div>
                <div class="card-body">
                  @include('layouts.partials.errors')

                  <form method="post" action="{{ route('apps.store') }}" enctype="multipart/form-data" >
                      @csrf
                      @include('apps.partials.form')
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/apps/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create App</div>
                <div class="card-body">
                  App card
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/apps/partials/form.blade.php
<form>
  @component('layouts.components.box', ['title' => 'Informações Básica'])
  <div class="row">
    <div class="col-md-6">
        <label for="inputZip">Nome do App</label>
        <input type="text" class="form-control" name="app_name" value="{{ old('app_name') }}">
    </div>
    <div class="col-md-6">
        <label for="inputZip">Nome do App no telefone</label>
        <input type="text" class="form-control" name="app_display_name" value="{{ old('app_display_name') }}" >
    </div>
  </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Definições de Cores'])
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tab_icon_default</label>
          <input type="color" class="form-control" name="config[tab_icon_default]" >
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tint_color</label>
          <input type="color" class="form-control" name="config[tint_color]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">tab_bar</label>
          <input type="color" class="form-control" name="config[tab_bar]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">error_background</label>
          <input type="color" class="form-control" name="config[error_background]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">error_text</label>
          <input type="color" class="form-control" name="config[error_text]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">warning_background</label>
          <input type="color" class="form-control" name="config[warning_background]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">warning_text</label>
          <input type="color" class="form-control" name="config[warning_text]">
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">notice_text</label>
          <input type="color" class="form-control" name="config[notice_text]">
      </div>
    </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Imagens'])
    <div class="row">
      <div class="col-md-6">
          <label for="inputZip">Ícone do App (512x512) </label>
          <input type="file"  name="config[app_icon]">
      </div>

      <div class="col-md-6">
          <label for="inputZip">Splash Screen (2208x2208)</label>
          <input type="file"  name="config[app_splash_screen]" >
      </div>
    </div>
  @endcomponent

  @component('layouts.components.box', ['title' => 'Publicação'])
    @component('layouts.components.box', ['title' => 'Credencias do Expo'])
    <div class="row">
        <div class="col-md-6">
            <label for="inputZip">Usuário</label>
            <input type="text" class="form-control" name="config[expo_user]">
        </div>

        <div class="col-md-6">
            <label for="inputZip">Senha</label>
            <input type="password" class="form-control" name="config[expo_password]">
        </div>
      </div>
    @endcomponent
  @endcomponent

  <button type="submit" class="btn btn-primary">Create</button>
</form>

resources/views/build_log/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <b> Build {{$build->id}}</b> logs
                </div>

                <div class="card-body">
                    @component('layouts.components.box', ['title' => 'Logs'])
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">type</th>
                            <th scope="col">command</th>
                            <th scope="col">result</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($logs as $log)
                            <tr>
                                <th scope="row">{{ $log->id }}</th>
                                <td>{{ $log->type }}</td>
                                <td>{{ $log->command }}</td>
                                <td>{{ $log->result }}</td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard
                <a href="{{ route('apps.create')}}" class="btn btn-primary float-right">New App</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @component('layouts.components.box', ['title' => 'Apps'])
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Icon</th>
                            <th scope="col">Name</th>
                            <th scope="col">Num. Builds</th>
                            <th scope="col">...</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($apps as $app)
                            <tr>
                                <th scope="row">{{ $app->id }}</th>
                                <td>
                                  <img src="{{ asset($app->latestBuild()->config['app_icon']) }}" alt="">
                                </td>
                                <td>{{ $app->app_name }}</td>
                                <td>{{ $app->unProcessedBuilds->count() }}</td>
                                <td>
                                    @component('layouts.components.buttons.dropdowns_buttons', [ 'title' => '...'])
                                      <a class="dropdown-item" href="{{ route('apps.builds.create', $app) }}">New Build</a>
                                      <a class="dropdown-item" href="{{ route('apps.builds.index', $app) }}">See All Builds</a>
                                    @endcomponent
                                </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {{ $apps->links() }}
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        @include('layouts.partials.navbar')

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/components/box.blade.php
<div class="row">
  <div class="col-md-12 p-3">
    <div class="card">
      <div class="card-header">{{ $title }}</div>
      <div class="card-body">
        {{ $slot }}
      </div>
    </div>
  </div>
</div>

resources/views/layouts/components/buttons/dropdowns_buttons.blade.php
<div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ $title }}
    </button>
    <div class="dropdown-menu">
        {{ $slot }}
    </div>
  </div>

resources/views/layouts/partials/errors.blade.php
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
  <div class="container">
      <a class="navbar-brand" href="{{ url('/') }}">
          {{ config('app.name', 'Laravel') }}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
              <!-- Authentication Links -->
              @guest
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
              </li>
              @if (Route::has('register'))
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
              </li>
              @endif
              @else
              <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
              @endguest
          </ul>
      </div>
  </div>
</nav>